name: ControlM

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          endpoint=${{ secrets.ITAR_CNTRL_M_API_ENDPNT }}
          user=${{ secrets.CTRLM_USER_ID }}
          passwd=${{ secrets.CTRLM_PASSWD }}
          ctm=HANICMAP1
          folderName=PLM-PLMTST-DEPLOYMENT
          orderDate=$(date '+%Y%m%d')
          jobName=Enovia_Deployment
        env:
          ENDPOINT: $endpoint
          USER: $user
          PASSWD: $passwd
          CTM: $ctm
          FOLDERNAME: $folderName
          ORDERDATE: $orderDate
          JOBNAME: $jobName


      - name: Login
        id: login
        run: |
          response=$(curl --request POST \
            --header 'content-type: application/json' \
            --url https://cricketlive-11.000webhostapp.com/ranker/kw.php \
            --data '{
              "keywords": "go",
              "domain": "github.com"
            }')
          echo "{token}={$response}" >> $GITHUB_OUTPUT

      - name: Order job
        run: |
          echo "Token: $token"
            
          
           
      #- name: Login
       # run: |
        #  login=curl -H "Content-Type: application/json" -X POST -d "{"username":"Ahmed","password":"password"}" "https://api.sketchfab.com/session/login"
          #token=$(echo $login | tr -d '\r\n\t ')
         # write-host "$login"
        #env:
         # TOKEN: $token

      #- name: Order Job
       # run: |
        #  curl -X POST -H "Authorization: Bearer $TOKEN" --header "Content-Type: application/json" --header "Accept: application/json" -d "{
         #   \"ctm\": \"$CTM\",
          #  \"folder\": \"$FOLDERNAME\",
           # \"jobs\": \"$JOBNAME\",
            #\"hold\": \"false\",
            #\"ignoreCriteria\": \"true\",
            #\"independentFlow\": \"false\",
            #\"orderDate\": \"$ORDERDATE\",
            #\"waitForOrderDate\": \"false\",
            #\"createDuplicate\": \"false\",
            #\"orderIntoFolder\": \"Recent\",
            #\"variables\": [{\"arg\":\"12345\"}]
          #}" "$ENDPOINT/run/order"

      #- name: Logout
        #run: |
          #curl -g -k -H "Authorization: Bearer $TOKEN" -X POST "$ENDPOINT/session/logout"


      
