on:
  workflow_dispatch:
    inputs:
      name:
        description: 'FolderName'
        default: '16_OCT_2023'
        required: true
      environment:
        description: 'Environment Type (DEV, TST, PROD)'
        default: 'DEV'
        required: true

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up FTP
        run: |
          # Determine the target server based on the environment type
          case ${{ github.event.inputs.environment }} in
            "DEV")
              FTP_SERVER="${{ secrets.DEV_SERVER }}"
              ;;
            "TST")
              FTP_SERVER="${{ secrets.TST_SERVER }}"
              ;;
            "PROD")
              FTP_SERVER="${{ secrets.PROD_SERVER }}"
              ;;
            *)
              echo "Invalid environment type provided."
              exit 1
              ;;
          done

          # You can now use $FTP_SERVER in your FTP commands
          # For example: lftp -u $FTP_USER,$FTP_PASSWORD $FTP_SERVER
