name: Deploy to Hostinger via FTP

on:
  workflow_dispatch:  # Enable manual execution

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up FTP
        run: |
          sudo apt-get -y install lftp
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

      - name: Build Code
        run: |
          # Add your build commands here
          # Example: npm install, npm run build, or any build process

      - name: Create ZIP Archive
        run: |
          # Add commands to create a ZIP archive of your build output
          zip -r my_code.zip build/
          # Replace with your actual build commands

      - name: Upload ZIP Archive to Hostinger via FTP
        run: |
          # Install the required tools if not already installed
          sudo apt-get -y install lftp

          # Create a script file to upload the ZIP archive via FTP
          echo "open -u $FTP_USER,$FTP_PASSWORD $FTP_SERVER" > ftp_commands
          echo "cd ~/" >> ftp_commands  # Replace with your desired destination directory
          echo "put my_code.zip" >> ftp_commands    # Replace with your ZIP archive filename
          echo "bye" >> ftp_commands

          # Use lftp to execute the FTP commands from the script file
          lftp -f ftp_commands
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
