name: Deploy to Linux Server via SCP

on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: 'Folder to Zip and Deploy'
        required: true

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Copy specific folder to build directory
      run: |
        #mkdir ../build
        cp -r PLM_SOURCE/BUILD_MASTER/${{ github.event.inputs.folder_name }} ../build
        tar -cvf ${{ github.event.inputs.folder_name }}.tar -C ../build .

    - name: Copy file via SCP
      run: |
        scp -P ${{ secrets.PORT }} -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} "${{ github.event.inputs.folder_name }}.tar" ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/u813984108/domains/sociocast.co/public_html/scimail

    - name: Check out the repository to the runner
      uses: actions/checkout@v4  

    - name: Make the script files executable
      run: chmod +x my-script.sh

    - name: Run the scripts
      run: |
        ./my-script.sh
