name: Deploy to Linux Server via SCP


on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: 'Folder to Zip and Deploy'
        required: true
      choice:
        type: choice
        description: 'Environment Variable'
        options:
          - Dev
          - Test
          - Deploy

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Create ZIP Archive
      run: |
          # Add commands to create a ZIP archive of your project in the root directory 
          cd PLM_SOURCE/BUILD_MASTER
          zip -r ${{ github.event.inputs.folder_name }}.zip ${{ github.event.inputs.folder_name }}

    - name: Create and upload artifact
      uses: actions/upload-artifact@v2
      with:
         name: ${{ github.event.inputs.folder_name }}.zip
         path: PLM_SOURCE/BUILD_MASTER/${{ github.event.inputs.folder_name }}.zip
    
    - name: Download .tar file to the runner
      uses: actions/download-artifact@v2
      with:
        name: ${{ github.event.inputs.folder_name }}.zip

    - name: List downloaded files
      run: ls -al


   #- name: Check out the repository to the runner
      #uses: actions/checkout@v4  
    #- name: Make the script files executable
      #run: chmod +x my-script.sh
    #- name: Run the scripts
      #run: |
