name: Deploy to Hostinger Server via SCP

on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: 'Folder to Zip and Deploy'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Copy specific folder to build directory
      run: |
        mkdir ../build
        cp -r PLM_SOURCE/BUILD_MASTER/16_OCT_2023 ../build
        zip -r deploy.zip ../build

    - name: Copy file via SSH password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "deploy.zip"
        target: "./scimail"
