name: Deploy to Hostinger Server via SCP

on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: 'Folder to Zip and Deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create ZIP Archive
        run: |
          # Navigate to the specified folder
          #cd ${{ github.workspace }}/${{ github.event.inputs.folder_name }}
          # Create a ZIP archive of the folder
          zip -r deploy.zip .
        working-directory: ${{ github.workspace }}

      - name: Copy to Hostinger via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }} # You can also use SSH key authentication
          port: ${{ secrets.PORT }}
          source: "deploy.zip"
          target: "/scimail/"
