name: Deploy to Linux Server via SCP

on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: 'Folder to Zip and Deploy'
        required: true

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Copy specific folder to build directory
      run: |
        #mkdir ../build
        #cp -r PLM_SOURCE/BUILD_MASTER/${{ github.event.inputs.folder_name }} ../build
        #tar -cvf ${{ github.event.inputs.folder_name }}.tar -C ../build .

        cd PLM_SOURCE/BUILD_MASTER
        zip -r ${{ github.event.inputs.folder_name }}.zip ${{ github.event.inputs.folder_name }}

    - name: Copy file via SCP
      run: |
        $command = "scp -P $env:PORT -o StrictHostKeyChecking=no -i `"$env:SSH_PRIVATE_KEY`" `"$env:github_event_inputs_folder_name.zip`" `"$env:USERNAME@$env:HOST:/home/u813984108/domains/sociocast.co/public_html/scimail/`""
        Invoke-Expression -Command $command
        
    - name: Check out the repository to the runner
      uses: actions/checkout@v4  

    - name: Make the script files executable
      run: chmod +x my-script.sh

    - name: Run the scripts
      run: |
        ./my-script.sh
