name: Deploy to Linux Server via SCP

on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: 'Folder to Zip and Deploy'
        required: true
      environment_type:
        description: 'Environment Type'
        required: true
        options:
          - Dev
          - Test
          - Deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Copy specific folder to build directory
      run: |
        mkdir ../build
        cp -r PLM_SOURCE/BUILD_MASTER/${{ github.event.inputs.folder_name }} ../build
        tar -cvf ${{ github.event.inputs.folder_name }}.tar -C ../build .
        
    - name: Set Environment Variables based on Environment Type
      run: |
        if [[ "${{ github.event.inputs.environment_type }}" == "Dev" ]]; then
          export HOST="${{ secrets.HOST }}"
          export USERNAME="${{ secrets.USERNAME }}"
          export PASSWORD="${{ secrets.PASSWORD }}"
          export SSH_PRIVATE_KEY="${{ secrets.SSH_PRIVATE_KEY }}"
        elif [[ "${{ github.event.inputs.environment_type }}" == "Test" ]]; then
          export HOST="${{ secrets.HOST_TEST }}"
          export USERNAME="${{ secrets.USERNAME_TEST }}"
          export PASSWORD="${{ secrets.PASSWORD_TEST }}"
          export SSH_PRIVATE_KEY="${{ secrets.SSH_PRIVATE_KEY_TEST }}"
        elif [[ "${{ github.event.inputs.environment_type }}" == "Deploy" ]]; then
          export HOST="${{ secrets.HOST_DEPLOY }}"
          export USERNAME="${{ secrets.USERNAME_DEPLOY }}"
          export PASSWORD="${{ secrets.PASSWORD_DEPLOY }}"
          export SSH_PRIVATE_KEY="${{ secrets.SSH_PRIVATE_KEY_DEPLOY }}"
        else
          echo "Invalid environment type selected."
          exit 1
        fi

    - name: Copy file via SSH password
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.HOST }}
        username: ${{ env.USERNAME }}
        password: ${{ env.PASSWORD }}
        key: ${{ env.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "${{ github.event.inputs.folder_name }}.tar"
        target: "/home/u813984108/domains/sociocast.co/public_html/scimail/"

    - name: Check out the repository to the runner
      uses: actions/checkout@v4  
    - name: Make the script files executable
      run: chmod +x my-script.sh
    - name: Run the scripts
      run: |
        ./my-script.sh
