name: Deploy to Linux Server via SCP

on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: 'Folder to Zip and Deploy'
        required: true
      choice:
        type: choice
        description: 'Environment Variable'
        options:
          - Dev
          - Test
          - Deploy

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Create ZIP Archive
      run: |
          # Add commands to create a ZIP archive of your project in the root directory 
          cd PLM_SOURCE/BUILD_MASTER
          zip -r ${{ github.event.inputs.folder_name }}.zip ${{ github.event.inputs.folder_name }}
          
          # Check if the zip command was successful
          if ($?) {
            Write-Host "ZIP archive creation successful"
          } else {
            Write-Host "ZIP archive creation failed"
            exit 1  # Exit with an error code
          }

    - name: Create and upload artifact
      uses: actions/upload-artifact@v2
      with:
         name: ${{ github.event.inputs.folder_name }}.zip
         path: PLM_SOURCE/BUILD_MASTER/${{ github.event.inputs.folder_name }}.zip

    - name: Move the downloaded .zip file to D:/office/DBA
      run: |
        $destinationPath = "D:\office\DBA\${{ github.event.inputs.folder_name }}.zip"
        if (Test-Path -Path $destinationPath) {
           Write-Host "File already exists: $destinationPath"
             } 
        else {
           Move-Item -Path "$GITHUB_WORKSPACE/actions-runner/_work/array/array/PLM_SOURCE/BUILD_MASTER/${{ github.event.inputs.folder_name }}.zip" -Destination $destinationPath
            }




    #- name: List downloaded files
      #run: ls -al


    - name: Run my-script.sh
      run: |
        $scriptPath = "D:\office\DBA\my-script.sh"
        if (Test-Path -Path $scriptPath -PathType Leaf) {
           cd D:\office\DBA
           #chmod +x my-script.sh
           #./my-script.sh
            # Grant execute permission to the script
           icacls "$scriptPath" /grant:r "%USERNAME%:RX"
      
          # Run the script
           ./my-script.sh
          } 
        else {
          Write-Host "Error: my-script.sh not found in D:\office\DBA"
           }


