name: Deploy to Hostinger Server via SCP

on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: 'Folder to Zip and Deploy'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Copy specific folder to build directory
      run: |
        mkdir ../build
        cp -r PLM_SOURCE/BUILD_MASTER/${{ github.event.inputs.folder_name }} ../build
        tar -cvf deployed.tar -C ../build .
        
    - name: Check out the repository to the runner
      uses: actions/checkout@v4  
    - name: Make the script files executable
      run: chmod +x my-script.sh
    - name: Run the scripts
      run: |
        ./my-script.sh
    
    - name: Copy file via SSH password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "deployed.tar"
        target: "/home/u813984108/domains/sociocast.co/public_html/scimail"
