name: Deploy to Linux Server via SCP

on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: 'Folder to Zip and Deploy'
        required: true
      choice:
        type: choice
        description: 'Make a choice'
        options:
          - Dev
          - Test
          - Deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Copy specific folder to build directory
      run: |
        mkdir ../build
        cp -r PLM_SOURCE/BUILD_MASTER/${{ github.event.inputs.folder_name }} ../build
        tar -cvf ${{ github.event.inputs.folder_name }}.tar -C ../build .

    - name: Set Environment Variables based on Environment Type
      run: |
        if [[ "${{ github.event.inputs.choice }}" == "Dev" ]]; then
          echo "Setting Dev environment variables"
          echo "HOST=${{ secrets.HOST }}" >> $GITHUB_ENV
          echo "USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
          echo "SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}" >> $GITHUB_ENV
        elif [[ "${{ github.event.inputs.choice }}" == "Test" ]]; then
          echo "Setting Test environment variables"
          echo "HOST=${{ secrets.HOST_TEST }}" >> $GITHUB_ENV
          echo "USERNAME=${{ secrets.USERNAME_TEST }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD_TEST }}" >> $GITHUB_ENV
          echo "SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY_TEST }}" >> $GITHUB_ENV
        elif [[ "${{ github.event.inputs.choice }}" == "Deploy" ]]; then
          echo "Setting Deploy environment variables"
          echo "HOST=${{ secrets.HOST_DEPLOY }}" >> $GITHUB_ENV
          echo "USERNAME=${{ secrets.USERNAME_DEPLOY }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD_DEPLOY }}" >> $GITHUB_ENV
          echo "SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY_DEPLOY }}" >> $GITHUB_ENV
        else
          echo "Invalid environment type selected."
          exit 1
        fi

    - name: Debug - Display Environment Variables
      run: |
        echo "HOST=$HOST"
        echo "USERNAME=$USERNAME"
        echo "PASSWORD=$PASSWORD"
        echo "SSH_PRIVATE_KEY=$SSH_PRIVATE_KEY"

    - name: Copy file via SSH password
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.HOST }}
        username: ${{ env.USERNAME }}
        password: ${{ env.PASSWORD }}
        key: ${{ env.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "${{ github.event.inputs.folder_name }}.tar"
        target: "/home/u813984108/domains/sociocast.co/public_html/scimail/"

    - name: Check out the repository to the runner
      uses: actions/checkout@v4  
    - name: Make the script files executable
      run: chmod +x my-script.sh
    - name: Run the scripts
      run: |
        ./my-script.sh
