name: Deploy to Linux Server via SCP

on:
  workflow_dispatch: # Enable manual execution
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'FolderName'
        # Default value if no value is explicitly provided
        default: '16_OCT_2023'
        # Input has to be provided for the workflow to run
        required: true
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      #- name: Set Up FTP
      #  run: |
      #    sudo apt-get -y install lftp
      #  env:
      #    FTP_SERVER: ${{ secrets.FTP_SERVER }}
      #    FTP_USER: ${{ secrets.FTP_USER }}
      #    FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

      - name: Create ZIP Archive
        run: |
          # Add commands to create a ZIP archive of your project in the root directory 
          cd PLM_SOURCE/BUILD_MASTER
          zip -r ${{ github.event.inputs.name }}.zip .

      - name: Copy files via SSH password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "${{ github.event.inputs.name }}.zip"
          target: /scimail
