name: Deploy to Linux Server via SCP

on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: 'Folder to Zip and Deploy'
        required: true

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Copy specific folder to build directory
      run: |
        #mkdir ../build
        #cp -r PLM_SOURCE/BUILD_MASTER/${{ github.event.inputs.folder_name }} ../build
        #tar -cvf ${{ github.event.inputs.folder_name }}.tar -C ../build .

        cd PLM_SOURCE/BUILD_MASTER
        zip -r ${{ github.event.inputs.folder_name }}.zip ${{ github.event.inputs.folder_name }}

    - name: Copy file via SSH password
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        local: "${{ github.event.inputs.folder_name }}.tar"
        remote: "/home/u813984108/domains/sociocast.co/public_html/scimail"
        
    - name: Check out the repository to the runner
      uses: actions/checkout@v4  

    - name: Make the script files executable
      run: chmod +x my-script.sh

    - name: Run the scripts
      run: |
        ./my-script.sh
